
ROOT=$(shell git rev-parse --show-toplevel)
SUBPATH=$(shell $(ROOT)/cut-path.sh $(ROOT) ${PWD})

# CR-someday:
# https://stackoverflow.com/questions/10451242/how-to-adjust-the-path-that-emacs-compile-goto-error-gets-from-the-compilation
build:
	echo "Entering directory '${PWD}'"
	dune build ${JS:.js=.bc.js}
	dune runtest

%.js: FORCE
	cp ${ROOT}/_build/default/$(SUBPATH)/$*.bc.js $@

index.html: 
	ln -s  ${ROOT}/html/index-client-light.html $@

index-rain.html:
	ln -s  ${ROOT}/spark/html/$@

index-load.html:
	ln -s  ${ROOT}/spark/html/$@

external:
	ln -s  ${ROOT}/external .

start.sh:
	ln -s  ${ROOT}/start.sh

stop.sh:
	ln -s  ${ROOT}/stop.sh

clean:
	dune clean

FORCE:
